# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w  # Strip debug info
    main: .

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}@{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  draft: true
