version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  dev:ui:
    desc: Run development UI server
    cmds:
      - cd pkg/template/ui; pnpm dev --open

  build:ui:
    desc: Build Vue UI template
    cmds:
      - cd pkg/template/ui; pnpm build; cd -

  build:cli:
    desc: Build the binary 
    cmds:
      - go build -o ./bin/vizb

  build:
    desc: Build the UI & binary
    cmds:
      - task: build:ui
      - task: build:cli

  test:
    desc: Run all tests (no cache)
    cmds:
      - go test -count=1 -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  release:
    desc: Create and push a new tag to trigger release
    prompt: This will create and push a new release tag. Continue?
    vars:
      VERSION: '{{.CLI_ARGS | default "v0.1.0"}}'
    cmds:
      - echo "Creating tag {{.VERSION}}..."
      - git tag -a {{.VERSION}} -m "Release {{.VERSION}}"
      - git push origin {{.VERSION}}
      - echo "Tag {{.VERSION}} pushed. GitHub Actions will create the release."
