version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  dev:ui:
    desc: Run development UI server
    cmds:
      - cd pkg/template/ui; pnpm dev --open

  build:ui:
    desc: Build Vue UI template
    cmds:
      - cd pkg/template/ui; SINGLEFILE=True pnpm build; cd -

  build:cli:
    desc: Build the binary (production-ready, stripped)
    cmds:
      - go build -ldflags="-s -w" -o ./bin/vizb

  build:
    desc: Build the UI & binary
    cmds:
      - task: build:ui
      - task: build:cli

  test:
    desc: Run all tests (no cache)
    cmds:
      - go test -count=1 -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  format:
    desc: Format codes
    cmds:
      - gofmt -w .
      - cd pkg/template/ui; pnpm format; cd -

  release:check:
    desc: Check Goreleaser configuration
    cmds:
      - goreleaser check

  release:snapshot:
    desc: Create a snapshot release
    cmds:
      - goreleaser release --snapshot --clean

  release:
    desc: Create and push a new tag to trigger release
    prompt: This will create and push a new release tag. Continue?
    vars:
      VERSION: '{{.CLI_ARGS}}'
    cmds:
      - task: release:check
      - task: release:snapshot
      - echo "Creating tag {{.VERSION}}..."
      - git tag -a {{.VERSION}} -m "Release {{.VERSION}}"
      - git push origin {{.VERSION}}
      - echo "Tag {{.VERSION}} pushed. GitHub Actions will create the release."
