import { defineConfig, type PluginOption } from "vite";
import vue from "@vitejs/plugin-vue";
import { viteSingleFile } from "vite-plugin-singlefile";
import { createHtmlPlugin } from "vite-plugin-html";
import fs from "node:fs";
import path from "path";
import { parseHTML } from "linkedom";

const faviconPath = path.resolve(__dirname, "public/vizb.svg");

const inlineFaviconPlugin = (): PluginOption => {
  let faviconDataUrl: string | null = null;

  return {
    name: "inline-favicon",
    enforce: "post" as const,
    transformIndexHtml(html: string) {
      if (!faviconDataUrl) {
        const svg = fs.readFileSync(faviconPath, "utf-8");
        faviconDataUrl = `data:image/svg+xml,${encodeURIComponent(svg)}`;
      }

      return html.replace(
        /href=(["'])\.?\/vizb\.svg\1/,
        `href=$1${faviconDataUrl}$1`,
      );
    },
  };
};

const appendVizbDataScriptTag = (html: string): string => {
  const { document } = parseHTML(html);

  const script = document.createElement("script");
  script.type = "text/javascript";
  script.textContent = `window.VIZB_VERSION = {{ .Version }}; window.VIZB_DATA = {{ .Data }};`;

  document.head.appendChild(script);

  return "<!DOCTYPE html>" + document.documentElement.outerHTML;
};

const benchmarkUiGoWrapperPlugin = (): PluginOption => {
  const distHtmlPath = path.resolve(__dirname, "dist/index.html");
  const goFilePath = path.resolve(__dirname, '..', "vizb-ui.gen.go");

  return {
    name: "benchmark-ui-go-wrapper",
    apply: "build",
    closeBundle() {
      if (!fs.existsSync(distHtmlPath)) {
        console.warn(
          `[benchmark-ui-go-wrapper] Unable to find ${distHtmlPath}, skipping Go wrapper generation.`,
        );
        return;
      }

      const htmlContent = fs.readFileSync(distHtmlPath, "utf-8");
      const htmlWithState = appendVizbDataScriptTag(htmlContent);
      
      // Escape backticks for Go raw string literal
      const goRawString = htmlWithState.split("`").join('` + "`" + `');

      const goFileContent = `package template

// Code generated by vite.config.ts; DO NOT EDIT.

const vizbHTMLTemplate = \`${goRawString}\`
`;

      fs.writeFileSync(goFilePath, goFileContent, "utf-8");
    },
  };
};

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(), 
    viteSingleFile({
      removeViteModuleLoader: true,
      useRecommendedBuildConfig: true,
    }),
    createHtmlPlugin({
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        minifyCSS: true,
        minifyJS: true,
      },
    }),
    inlineFaviconPlugin(),
    benchmarkUiGoWrapperPlugin(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  esbuild: {
    legalComments: 'none',
    pure: ['console.log', 'console.info', 'console.warn', 'console.debug', 'console.trace'],
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
});
