import { defineConfig, type PluginOption } from 'vite'
import vue from '@vitejs/plugin-vue'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { createHtmlPlugin } from 'vite-plugin-html'
import fs from 'node:fs'
import path from 'path'
import { parseHTML } from 'linkedom'

const inlineFaviconPlugin = (): PluginOption => {
  return {
    name: 'inline-favicon',
    enforce: 'pre',
    transformIndexHtml(html: string) {
      const { document } = parseHTML(html)
      const link = document.querySelector('link[rel="icon"]')

      if (!link) {
        return html
      }

      const href = link.getAttribute('href')
      if (!href) return html

      // Try to resolve the file path, checking the public directory if needed
      let faviconPath = path.resolve(__dirname, href)

      if (!fs.existsSync(faviconPath)) {
        faviconPath = path.resolve(__dirname, 'public', href)
      }

      if (!fs.existsSync(faviconPath)) {
        console.warn(`[inline-favicon] Could not locate favicon: ${href}`)
        return html
      }

      const source = fs.readFileSync(faviconPath, 'utf-8')
      link.setAttribute('href', `data:${link.getAttribute('type')},${encodeURIComponent(source)}`)

      return '<!DOCTYPE html>' + document.documentElement.outerHTML
    },
  }
}

const appendVizbDataScriptTag = (html: string): string => {
  const { document } = parseHTML(html)

  const script = document.createElement('script')
  script.type = 'text/javascript'
  script.textContent = `window.VIZB_VERSION = {{ .Version }}; window.VIZB_DATA = {{ .Data }};`

  document.head.appendChild(script)

  return '<!DOCTYPE html>' + document.documentElement.outerHTML
}

const benchmarkUiGoWrapperPlugin = (): PluginOption => {
  const distHtmlPath = path.resolve(__dirname, 'dist/index.html')
  const goFilePath = path.resolve(__dirname, '..', 'vizb-ui.gen.go')

  return {
    name: 'benchmark-ui-go-wrapper',
    apply: 'build',
    closeBundle() {
      if (!fs.existsSync(distHtmlPath)) {
        console.warn(
          `[benchmark-ui-go-wrapper] Unable to find ${distHtmlPath}, skipping Go wrapper generation.`
        )
        return
      }

      const htmlContent = fs.readFileSync(distHtmlPath, 'utf-8')
      const htmlWithState = appendVizbDataScriptTag(htmlContent)

      // Escape backticks for Go raw string literal
      const goRawString = htmlWithState.split('`').join('` + "`" + `')

      const goFileContent = `package template

// Code generated by vite.config.ts; DO NOT EDIT.

const VizbHTMLTemplate = \`${goRawString}\`
`

      fs.writeFileSync(goFilePath, goFileContent, 'utf-8')
    },
  }
}

const singleFile = process.env.SINGLEFILE === 'True'
console.info('SINGLEFILE env var:', process.env.SINGLEFILE)

const plugins: PluginOption[] = [vue()]

if (singleFile) {
  plugins.push(
    inlineFaviconPlugin(),
    viteSingleFile({
      removeViteModuleLoader: true,
      useRecommendedBuildConfig: true,
    }),
    benchmarkUiGoWrapperPlugin()
  )
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    ...plugins,
    createHtmlPlugin({
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        minifyCSS: true,
        minifyJS: true,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  esbuild: {
    legalComments: 'none',
    pure: ['console.log', 'console.info', 'console.warn', 'console.debug', 'console.trace'],
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
})
