<script setup lang="ts">
import { computed, watch } from "vue";
import { Moon, Sun } from "lucide-vue-next";
import { useBenchmarkData } from "../composables/useBenchmarkData";
import { useChartData } from "../composables/useChartData";
import { useSettingsStore } from "../composables/useSettingsStore";
import ChartSettingsPopover from "../components/ChartSettingsPopover.vue";
import BenchmarkGroupSelector from "../components/BenchmarkGroupSelector.vue";
import ChartCard from "../components/ChartCard.vue";
import AccentLink from "../components/AccentLink.vue";
import IconButton from "../components/IconButton.vue";
import type { Benchmark } from "../types/benchmark";

const version = window.VIZB_VERSION || 'v0.0.0-dev'

const {
  // Top level benchmark selection
  benchmarks,
  activeBenchmark,
  activeBenchmarkId,
  selectBenchmark,

  // Inner level group selection
  resultGroups,
  activeGroup,
  activeGroupId,
  selectGroup,
} = useBenchmarkData();

// Use the active group's results for chart data
const activeResults = computed(() => activeGroup.value?.data || []);
const { chartData } = useChartData(activeResults);

const { isDark, toggleDark, initializeFromBenchmark } = useSettingsStore();

// Initialize settings from the active benchmark settings
watch(
  activeBenchmark,
  (b) => {
    if (b?.settings) {
      initializeFromBenchmark(b.settings);
    }
  },
  { immediate: true }
);

// Get the main constant title (use description as main title)
const mainTitle = computed(() => {
  // Use the description from the first benchmark as the constant title
  return benchmarks.value[0]?.name || "Benchmarks";
});

const CPUtoString = (cpu: Benchmark['cpu']) => {
  if (cpu.name && cpu.cores) {
    return `${cpu.name} (${cpu.cores} cores)`;
  }

  if (cpu.name) {
    return cpu.name;
  }

  if (cpu.cores) {
    return `${cpu.cores} cores`;
  }

  return "";
};

const hasCPU = computed(() => activeBenchmark.value?.cpu?.name || activeBenchmark.value?.cpu?.cores);

</script>

<template>
  <main class="min-h-screen bg-background text-foreground">
    <!-- Top Right Controls -->
    <nav class="fixed top-6 right-6 z-50 flex items-center gap-2">
      <!-- Settings Popover -->
      <ChartSettingsPopover />

      <!-- Theme Toggle -->
      <IconButton
        @click="toggleDark()"
        aria-label="Toggle theme"
      >
        <Sun v-if="isDark" class="w-5 h-5" />
        <Moon v-else class="w-5 h-5" />
      </IconButton>
    </nav>

    <!-- Main Container -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Content -->
      <template v-if="activeBenchmark">
        <!-- Header with Benchmark Selector -->
        <header class="text-center space-y-3 mb-8">
          <h1 class="text-4xl flex items-center justify-center">
              <BenchmarkGroupSelector
                v-if="benchmarks.length > 1"
                :benchmarks="benchmarks"
                :activeBenchmarkId="activeBenchmarkId"
                @select="selectBenchmark"
                class="min-w-80"
                placeholder="Select Benchmark..."
              />
            <template v-else>
              {{ mainTitle }}
            </template>
          </h1>

          <span
            v-if="hasCPU"
            class="inline-flex items-center px-3 py-1 text-sm font-semibold rounded-lg border border-border bg-secondary text-secondary-foreground"
          >
            CPU: {{ CPUtoString(activeBenchmark.cpu) }}
          </span>
          
          <p v-if="activeBenchmark.description" class="text-muted-foreground">
            {{ activeBenchmark.description }}
          </p>

          <!-- Inner Group Selector -->
          <div v-if="resultGroups.length > 1" class="flex justify-center mb-8">
            <BenchmarkGroupSelector
              :benchmarks="resultGroups"
              :activeBenchmarkId="activeGroupId"
              @select="selectGroup"
              placeholder="Search Group..."
            />
          </div>
        </header>

        <!-- Charts Grid -->
        <div class="space-y-5">
          <ChartCard
            v-for="(chart, index) in chartData"
            :key="`${activeBenchmarkId}-${activeGroupId}-${index}`"
            :chartData="chart"
            class="animate-fade-in"
            :style="{ animationDelay: `${index * 50}ms` }"
          />
        </div>
      </template>
    </div>
  </main>

  <footer class="text-center space-y-2 mb-8 text-sm text-muted-foreground">
    Generated by
    <AccentLink href="https://github.com/goptics/vizb">
      Vizb
    </AccentLink>
    | Made with ❤ -
    <AccentLink href="https://github.com/goptics">
       Goptics
    </AccentLink>
    © {{ new Date().getFullYear() }}
    <p class="text-muted-foreground/50 pointer-events-none">
      {{ version }}
    </p>
  </footer>
</template>
