<script setup lang="ts">
import { computed, watch } from 'vue'
import { Moon, Sun, Package } from 'lucide-vue-next'
import { useBenchmarkData } from '../composables/useBenchmarkData'
import { useChartData } from '../composables/useChartData'
import { useSettingsStore } from '../composables/useSettingsStore'
import { useUrlRouter } from '../composables/useUrlRouter'
import ChartSettingsPopover from '../components/ChartSettingsPopover.vue'
import GroupSelector from '../components/Selector.vue'
import ChartCard from '../components/ChartCard.vue'
import IconButton from '../components/IconButton.vue'
import AccentLink from '../components/AccentLink.vue'
import { CPUtoString } from '../lib/utils'

const version = window.VIZB_VERSION || 'v0.0.0-dev'

const {
  // Top level benchmark selection
  benchmarks,
  activeBenchmark,
  activeBenchmarkId,
  selectBenchmark,

  // Inner level group selection
  resultGroups,
  activeGroup,
  activeGroupId,
  selectGroup,
} = useBenchmarkData()

// Use the active group's results for chart data
const activeResults = computed(() => activeGroup.value?.data || [])
const { chartData } = useChartData(activeResults)

const { settings, toggleDark, initializeFromBenchmark } = useSettingsStore()
const { initFromUrl } = useUrlRouter()

let urlInitialized = false

// Initialize settings from the active benchmark settings
watch(
  activeBenchmark,
  (b) => {
    if (b?.settings) {
      initializeFromBenchmark(b.settings)
    }
  },
  { immediate: true }
)

// Initialize from URL once benchmarks are loaded
watch(
  benchmarks,
  (b) => {
    if (b.length && !urlInitialized) {
      initFromUrl()
      urlInitialized = true
    }
  },
  { immediate: true }
)

// Get the main constant title (use description as main title)
const mainTitle = computed(() => {
  // Use the description from the first benchmark as the constant title
  return benchmarks.value[0]?.name || 'Benchmarks'
})

const hasCPU = computed(() => activeBenchmark.value?.cpu?.name || activeBenchmark.value?.cpu?.cores)
</script>

<template>
  <nav class="fixed right-6 top-6 z-50 flex items-center gap-2">
    <IconButton
      v-if="activeBenchmark?.pkg"
      :href="`https://${activeBenchmark.pkg}`"
      aria-label="View Package Source"
    >
      <Package class="h-5 w-5" />
    </IconButton>

    <ChartSettingsPopover />

    <IconButton @click="toggleDark()" aria-label="Toggle theme">
      <Sun v-if="settings.isDark" class="h-5 w-5" />
      <Moon v-else class="h-5 w-5" />
    </IconButton>
  </nav>

  <main v-if="activeBenchmark" class="mx-auto min-h-screen max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <header class="space-y-3 py-5 text-center">
      <GroupSelector
        v-if="benchmarks.length > 1"
        :items="benchmarks"
        :activeId="activeBenchmarkId"
        @select="selectBenchmark"
        class="mx-auto min-w-80"
        placeholder="Search Benchmark..."
        notFoundText="No benchmark found."
      />

      <h1 v-else class="text-4xl font-bold">{{ mainTitle }}</h1>

      <span
        v-if="hasCPU"
        class="inline-block rounded-lg border border-border bg-secondary px-2 py-1 text-sm font-semibold text-secondary-foreground"
        >CPU: {{ CPUtoString(activeBenchmark?.cpu) }}</span
      >

      <p v-if="activeBenchmark?.description" class="text-muted-foreground">
        {{ activeBenchmark?.description }}
      </p>

      <!-- Inner Group Selector -->
      <GroupSelector
        v-if="resultGroups.length > 1"
        :items="resultGroups"
        :activeId="activeGroupId"
        @select="selectGroup"
        placeholder="Search Group..."
        notFoundText="No group found."
        class="mx-auto min-w-80"
      />
    </header>

    <!-- Charts Grid -->
    <div class="space-y-5">
      <ChartCard
        v-for="(chart, index) in chartData"
        :key="`${activeBenchmarkId}-${activeGroupId}-${index}`"
        :chartData="chart"
        class="animate-fade-in"
        :style="{ animationDelay: `${index * 50}ms` }"
      />
    </div>
  </main>

  <footer v-if="activeBenchmark" class="pb-5 text-center text-sm text-muted-foreground">
    Generated by
    <AccentLink href="https://github.com/goptics/vizb"> Vizb </AccentLink>
    | Made with ❤️ -
    <AccentLink href="https://github.com/goptics"> Goptics </AccentLink>
    © {{ new Date().getFullYear() }}
    <p class="text-muted-foreground/50">
      {{ version }}
    </p>
  </footer>
</template>
