<script setup lang="ts">
import { computed } from "vue";
import { Moon, Sun } from "lucide-vue-next";
import { useBenchmarkData } from "../composables/useBenchmarkData";
import { useChartData } from "../composables/useChartData";
import { useSettingsStore } from "../composables/useSettingsStore";
import BenchmarkHeader from "../components/BenchmarkHeader.vue";
import ChartSettingsPopover from "../components/ChartSettingsPopover.vue";
import BenchmarkGroupSelector from "../components/BenchmarkGroupSelector.vue";
import ChartCard from "../components/ChartCard.vue";

const {
  benchmarks,
  activeBenchmark,
  activeBenchmarkId,
  selectBenchmark,
} = useBenchmarkData();

const activeResults = computed(() => activeBenchmark.value?.results || []);
const { chartData } = useChartData(activeResults);

const {
  sortOrder,
  showLabels,
  chartType,
  isDark,
  setSortOrder,
  setShowLabels,
  setChartType,
  toggleDark,
} = useSettingsStore();

// Get the main constant title (use description as main title)
const mainTitle = computed(() => {
  // Use the description from the first benchmark as the constant title
  return benchmarks.value[0]?.description || 'Benchmarks'
})

// No async loading needed since data is static
</script>

<template>
  <div class="min-h-screen bg-background text-foreground">
    <!-- Top Right Controls -->
    <div class="fixed top-6 right-6 z-50 flex items-center gap-2">
      <!-- Settings Popover -->
      <ChartSettingsPopover
        :chartType="chartType"
        :sortOrder="sortOrder"
        :showLabels="showLabels"
        @update:chartType="setChartType"
        @update:sortOrder="setSortOrder"
        @update:showLabels="setShowLabels"
      />

      <!-- Theme Toggle -->
      <button
        @click="toggleDark()"
        class="inline-flex items-center justify-center w-12 h-12 rounded-lg border border-border bg-card text-card-foreground hover:bg-accent hover:text-accent-foreground transition-colors shadow-sm"
        aria-label="Toggle theme"
      >
        <Sun v-if="isDark" class="w-5 h-5" />
        <Moon v-else class="w-5 h-5" />
      </button>
    </div>

    <!-- Main Container -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Content -->
      <template v-if="activeBenchmark">
        <!-- Header -->
        <BenchmarkHeader
          :benchmark="activeBenchmark"
          :mainTitle="mainTitle"
        />

        <!-- Bench Group Selector (if multiple groups) -->
        <div
          v-if="benchmarks.length > 1"
          class="flex justify-center mb-8"
        >
          <BenchmarkGroupSelector
            :benchmarks="benchmarks"
            :activeBenchmarkId="activeBenchmarkId"
            @select="selectBenchmark"
          />
        </div>

        <!-- Charts Grid -->
        <div class="grid grid-cols-1 gap-8">
          <ChartCard
            v-for="(chart, index) in chartData"
            :key="`${activeBenchmarkId}-${index}`"
            :chartData="chart"
            :sortOrder="sortOrder"
            :showLabels="showLabels"
            :isDark="isDark"
            :chartType="chartType"
            class="animate-fade-in"
            :style="{ animationDelay: `${index * 50}ms` }"
          />
        </div>

        <!-- Footer -->
        <footer class="text-center mt-16 mb-8 text-sm text-muted-foreground">
          Generated by
          <a
            href="https://github.com/goptics/vizb"
            target="_blank"
            class="text-foreground font-semibold hover:text-primary transition-colors"
          >
            Vizb
          </a>
          | Made with ❤ -
          <a
            href="https://github.com/goptics"
            target="_blank"
            class="text-foreground font-semibold hover:text-primary transition-colors"
          >
            Goptics
          </a>
          © 2025
        </footer>
      </template>
    </div>
  </div>
</template>

<style scoped>
@keyframes fade-in {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-in {
  animation: fade-in 0.5s ease-out backwards;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.animate-spin {
  animation: spin 1s linear infinite;
}
</style>
