import { defineConfig, type PluginOption } from "vite";
import vue from "@vitejs/plugin-vue";
import { viteSingleFile } from "vite-plugin-singlefile";
import { createHtmlPlugin } from "vite-plugin-html";
import fs from "node:fs";
import path from "path";

const faviconPath = path.resolve(__dirname, "public/vizb.svg");

const inlineFaviconPlugin = (): PluginOption => {
  let faviconDataUrl: string | null = null;

  return {
    name: "inline-favicon",
    enforce: "post" as const,
    transformIndexHtml(html: string) {
      if (!faviconDataUrl) {
        const svg = fs.readFileSync(faviconPath, "utf-8");
        faviconDataUrl = `data:image/svg+xml,${encodeURIComponent(svg)}`;
      }

      return html.replace(
        /href=(["'])\.?\/vizb\.svg\1/,
        `href=$1${faviconDataUrl}$1`,
      );
    },
  };
};

const benchmarkUiGoWrapperPlugin = (): PluginOption => {
  const distHtmlPath = path.resolve(__dirname, "dist/index.html");
  const goFilePath = path.resolve(__dirname, "benchmark_ui.gen.go");
  const placeholder = "{{BENCHMARK_DATA}}";

  return {
    name: "benchmark-ui-go-wrapper",
    apply: "build",
    closeBundle() {
      if (!fs.existsSync(distHtmlPath)) {
        console.warn(
          `[benchmark-ui-go-wrapper] Unable to find ${distHtmlPath}, skipping Go wrapper generation.`,
        );
        return;
      }

      const htmlContent = fs.readFileSync(distHtmlPath, "utf-8");
      const normalizedHtml = normalizeBenchmarkPlaceholder(
        htmlContent,
        placeholder,
      );
      const goLiteral = toGoRawStringLiteral(normalizedHtml);
      const goSource = `// Code generated by Vite build. DO NOT EDIT.

package ui

import "strings"

const benchmarkUITemplate = ${goLiteral}

func GenerateBenchmarkUI(benchmarkData []byte) string {
    return strings.ReplaceAll(benchmarkUITemplate, "${placeholder}", string(benchmarkData))
}
`;

      fs.writeFileSync(goFilePath, goSource, "utf-8");
    },
  };
};

const toGoRawStringLiteral = (content: string): string => {
  const segments = content.split("`");
  if (segments.length === 1) {
    return `\`${content}\``;
  }
  return segments.map((segment) => `\`${segment}\``).join(' + "`" + ');
};

const normalizeBenchmarkPlaceholder = (
  html: string,
  placeholder: string,
): string => {
  const pattern = new RegExp(
    "window\\.VIZB_DATA\\s*=\\s*['\"`]" +
      escapeForRegExp(placeholder) +
      "['\"`]",
  );

  if (!pattern.test(html)) {
    return html;
  }

  return html.replace(pattern, `window.VIZB_DATA=\`${placeholder}\``);
};

const escapeForRegExp = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(), 
    viteSingleFile({
      removeViteModuleLoader: true,
      useRecommendedBuildConfig: true,
    }),
    createHtmlPlugin({
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        minifyCSS: true,
        minifyJS: true,
      },
    }),
    inlineFaviconPlugin(),
    benchmarkUiGoWrapperPlugin(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  esbuild: {
    legalComments: 'none',
    pure: ['console.log', 'console.info', 'console.warn', 'console.debug', 'console.trace'],
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
});
