<script setup lang="ts">
defineProps<{ version: string }>()
</script>

<template>
  <footer class="pb-5 text-center text-sm text-muted-foreground">
    Generated by
    <a
      href="https://vizb.goptics.org"
      target="_blank"
      rel="noopener noreferrer"
      class="font-semibold text-foreground hover:text-primary"
    >
      Vizb
    </a>
    | Made with ❤️ -
    <a
      href="https://github.com/goptics"
      target="_blank"
      rel="noopener noreferrer"
      class="font-semibold text-foreground hover:text-primary"
    >
      Goptics
    </a>
    © {{ new Date().getFullYear() }}
    <p class="text-muted-foreground/50">{{ version }}</p>
  </footer>
</template>
