#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Topic slugs match dist/examples/<topic>/ and example workflow names
# (github-legends uses github-legends.yml without the -examples suffix).
ALL_TOPICS=(tabular-data math-and-3d comparisons github-legends go rust javascript)
ONLY_TOPICS=()
NO_OPEN=false
REUSE=false

usage() {
  cat <<'EOF'
Run example preparation workflows locally via act (skips site publishing).

Usage:
  ./scripts/act-examples.sh [options]

Options:
  --only TOPICS  Comma-separated subset:
                 tabular-data,math-and-3d,comparisons,github-legends,go,rust,javascript
  --no-open      Skip opening the overview in the default browser
  --reuse        Reuse act containers between runs (faster reruns)
  -h, --help     Show this help

Prerequisites: act (>= 0.2.50), Docker, Go 1.26+
EOF
}

workflow_for() {
  local topic="$1"
  case "$topic" in
    github-legends)
      echo ".github/workflows/github-legends.yml"
      ;;
    *)
      echo ".github/workflows/${topic}-examples.yml"
      ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --only)
      IFS=',' read -ra ONLY_TOPICS <<< "$2"
      shift 2
      ;;
    --no-open) NO_OPEN=true; shift ;;
    --reuse) REUSE=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ ${#ONLY_TOPICS[@]} -eq 0 ]]; then
  TOPICS=("${ALL_TOPICS[@]}")
else
  TOPICS=("${ONLY_TOPICS[@]}")
fi

for dep in act docker go; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    echo "Missing required tool: $dep" >&2
    exit 1
  fi
done

mkdir -p bin dist/examples .act/artifacts
rm -rf .act/jsons
mkdir -p .act/jsons

echo "Building vizb..."
go build -o bin/vizb .

ACT_ARGS=(workflow_dispatch --input publish=false)
if $REUSE; then
  ACT_ARGS+=(--reuse)
fi

for topic in "${TOPICS[@]}"; do
  wf="$(workflow_for "$topic")"
  if [[ ! -f "$wf" ]]; then
    echo "Unknown topic or missing workflow: $topic ($wf)" >&2
    exit 1
  fi
  echo "Running $wf via act..."
  rm -rf .act/jsons
  mkdir -p .act/jsons
  act "${ACT_ARGS[@]}" -W "$wf"

  # act bind-mount leaves ephemeral json at repo root
  rm -f bench.json
  find . -maxdepth 1 \( -name '[0-9][0-9]-*.json' -o -name '*.json' \) ! -name 'bench.json' -delete
done

write_overview() {
  local index="dist/examples/index.html"
  local built_topics=()

  for topic in "${TOPICS[@]}"; do
    if [[ -f "dist/examples/${topic}/index.html" ]]; then
      built_topics+=("$topic")
    fi
  done

  if [[ ${#built_topics[@]} -eq 0 ]]; then
    echo "No example galleries were produced under dist/examples/" >&2
    exit 1
  fi

  {
    echo '<!DOCTYPE html>'
    echo '<html lang="en">'
    echo '<head>'
    echo '  <meta charset="utf-8">'
    echo '  <meta name="viewport" content="width=device-width, initial-scale=1">'
    echo '  <title>Vizb Examples (local)</title>'
    echo '  <style>'
    echo '    body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 3rem auto; padding: 0 1rem; line-height: 1.5; }'
    echo '    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }'
    echo '    p { color: #555; margin-top: 0; }'
    echo '    ul { list-style: none; padding: 0; }'
    echo '    li { margin: 0.5rem 0; }'
    echo '    a { color: #0066cc; text-decoration: none; font-size: 1.1rem; }'
    echo '    a:hover { text-decoration: underline; }'
    echo '  </style>'
    echo '</head>'
    echo '<body>'
    echo '  <h1>Vizb Examples</h1>'
    echo '  <p>Local preview generated by <code>scripts/act-examples.sh</code></p>'
    echo '  <ul>'
    for topic in "${built_topics[@]}"; do
      echo "    <li><a href=\"${topic}/index.html\">${topic}</a></li>"
    done
    echo '  </ul>'
    echo '</body>'
    echo '</html>'
  } > "$index"

  echo "Overview written to $index"
}

open_browser() {
  local target
  target="$(cd dist/examples && pwd)/index.html"
  case "$(uname -s)" in
    Linux) xdg-open "$target" >/dev/null 2>&1 || true ;;
    Darwin) open "$target" ;;
    MINGW*|MSYS*|CYGWIN*) start "" "$target" ;;
    *) echo "Open $target in your browser" ;;
  esac
}

write_overview

if ! $NO_OPEN; then
  open_browser
fi
