// Code generated by qtc from "template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/chart/templates/template.qtpl:1
package templates

//line pkg/chart/templates/template.qtpl:3
import (
	"bytes"
	_ "embed"
	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/goptics/vizb/shared"
	"strings"
)

//line pkg/chart/templates/template.qtpl:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/chart/templates/template.qtpl:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/chart/templates/template.qtpl:12
//go:embed static/styles.css
var stylesCSS string

//go:embed static/chart.js
var chartJS string

//line pkg/chart/templates/template.qtpl:19
func StreamBenchmarkChart(qw422016 *qt422016.Writer, benchCharts []shared.BenchCharts) {
//line pkg/chart/templates/template.qtpl:19
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>`)
//line pkg/chart/templates/template.qtpl:24
	qw422016.E().S(shared.FlagState.Name)
//line pkg/chart/templates/template.qtpl:24
	qw422016.N().S(`</title>
    <script src="https://go-echarts.github.io/go-echarts-assets/assets/echarts.min.js"></script>
    <script src="https://go-echarts.github.io/go-echarts-assets/assets/themes/light.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        `)
//line pkg/chart/templates/template.qtpl:29
	qw422016.N().S(stylesCSS)
//line pkg/chart/templates/template.qtpl:29
	qw422016.N().S(`
    </style>
    <script type="text/javascript">
        `)
//line pkg/chart/templates/template.qtpl:32
	qw422016.N().S(chartJS)
//line pkg/chart/templates/template.qtpl:32
	qw422016.N().S(`
    </script>
</head>
<body>
    <!-- Sort Controls -->
    <div class="sort-controls">
        <span class="sort-label">Sort:</span>
        <button class="sort-btn active" data-sort="default" onclick="sortAllCharts('default')">Default</button>
        <button class="sort-btn" data-sort="asc" onclick="sortAllCharts('asc')">Ascending ↑</button>
        <button class="sort-btn" data-sort="desc" onclick="sortAllCharts('desc')">Descending ↓</button>
    </div>

    <h1>`)
//line pkg/chart/templates/template.qtpl:44
	qw422016.E().S(shared.FlagState.Name)
//line pkg/chart/templates/template.qtpl:44
	if shared.CPUCount > 0 {
//line pkg/chart/templates/template.qtpl:44
		qw422016.N().S(` (CPU: `)
//line pkg/chart/templates/template.qtpl:44
		qw422016.N().D(shared.CPUCount)
//line pkg/chart/templates/template.qtpl:44
		qw422016.N().S(`)`)
//line pkg/chart/templates/template.qtpl:44
	}
//line pkg/chart/templates/template.qtpl:44
	qw422016.N().S(`</h1>
    `)
//line pkg/chart/templates/template.qtpl:45
	if shared.FlagState.Description != "" {
//line pkg/chart/templates/template.qtpl:45
		qw422016.N().S(`
    <p style="text-align: center; margin-bottom: 20px;">`)
//line pkg/chart/templates/template.qtpl:46
		qw422016.E().S(shared.FlagState.Description)
//line pkg/chart/templates/template.qtpl:46
		qw422016.N().S(`</p>
    `)
//line pkg/chart/templates/template.qtpl:47
	}
//line pkg/chart/templates/template.qtpl:47
	qw422016.N().S(`

    `)
//line pkg/chart/templates/template.qtpl:50
	// Check if any benchmark has a non-empty name
	hasNamedBenchmarks := false
	for _, benchChart := range benchCharts {
		if benchChart.Name != "" {
			hasNamedBenchmarks = true
			break
		}
	}

	totalCharts := 0
	for _, benchChart := range benchCharts {
		totalCharts += len(benchChart.Charts)
	}

//line pkg/chart/templates/template.qtpl:63
	qw422016.N().S(`
    
    `)
//line pkg/chart/templates/template.qtpl:65
	if hasNamedBenchmarks && totalCharts > 2 {
//line pkg/chart/templates/template.qtpl:65
		qw422016.N().S(`
    <!-- Sidebar for benchmark navigation -->
    <div id="bench-sidebar" class="sidebar">
        <div class="sidebar-header">
            <div class="sidebar-title">Bench Groups</div>
            <button id="minimize-btn" class="minimize-btn">▶</button>
        </div>
        `)
//line pkg/chart/templates/template.qtpl:72
		for i, benchChart := range benchCharts {
//line pkg/chart/templates/template.qtpl:72
			qw422016.N().S(`
        `)
//line pkg/chart/templates/template.qtpl:73
			if benchChart.Name != "" {
//line pkg/chart/templates/template.qtpl:73
				qw422016.N().S(`
        <div class="bench-indicator`)
//line pkg/chart/templates/template.qtpl:74
				if i == 0 {
//line pkg/chart/templates/template.qtpl:74
					qw422016.N().S(` active`)
//line pkg/chart/templates/template.qtpl:74
				}
//line pkg/chart/templates/template.qtpl:74
				qw422016.N().S(`" data-target="bench-section-`)
//line pkg/chart/templates/template.qtpl:74
				qw422016.N().D(i)
//line pkg/chart/templates/template.qtpl:74
				qw422016.N().S(`">
            `)
//line pkg/chart/templates/template.qtpl:75
				qw422016.E().S(benchChart.Name)
//line pkg/chart/templates/template.qtpl:75
				qw422016.N().S(`
        </div>
        `)
//line pkg/chart/templates/template.qtpl:77
			}
//line pkg/chart/templates/template.qtpl:77
			qw422016.N().S(`
        `)
//line pkg/chart/templates/template.qtpl:78
		}
//line pkg/chart/templates/template.qtpl:78
		qw422016.N().S(`
    </div>
    `)
//line pkg/chart/templates/template.qtpl:80
	}
//line pkg/chart/templates/template.qtpl:80
	qw422016.N().S(`
    
    `)
//line pkg/chart/templates/template.qtpl:82
	for i, benchChart := range benchCharts {
//line pkg/chart/templates/template.qtpl:82
		qw422016.N().S(`
    <div id="bench-section-`)
//line pkg/chart/templates/template.qtpl:83
		qw422016.N().D(i)
//line pkg/chart/templates/template.qtpl:83
		qw422016.N().S(`" class="chart-section">
        `)
//line pkg/chart/templates/template.qtpl:84
		for _, chart := range benchChart.Charts {
//line pkg/chart/templates/template.qtpl:84
			qw422016.N().S(`
        <div class='chart'>
            `)
//line pkg/chart/templates/template.qtpl:86
			qw422016.N().S(renderChart(chart))
//line pkg/chart/templates/template.qtpl:86
			qw422016.N().S(`
        </div>
        `)
//line pkg/chart/templates/template.qtpl:88
		}
//line pkg/chart/templates/template.qtpl:88
		qw422016.N().S(`
    </div>
    `)
//line pkg/chart/templates/template.qtpl:90
	}
//line pkg/chart/templates/template.qtpl:90
	qw422016.N().S(`

    <footer style="text-align: center; margin-top: 30px; margin-bottom: 20px; font-size: 14px; color: #666;">
        Generated by <a alt="Vizb" target="_blank" href="https://github.com/goptics/vizb" style="color: #666; text-decoration: none; font-weight: bold;">Vizb</a> | Made with <span style="color: #e25555;">❤</span> -  <a alt="Goptics" target="_blank" href="https://github.com/goptics" style="color: #666; text-decoration: none; font-weight: bold;">Goptics</a> &copy; 2025
    </footer>
</body>
</html>
`)
//line pkg/chart/templates/template.qtpl:97
}

//line pkg/chart/templates/template.qtpl:97
func WriteBenchmarkChart(qq422016 qtio422016.Writer, benchCharts []shared.BenchCharts) {
//line pkg/chart/templates/template.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/chart/templates/template.qtpl:97
	StreamBenchmarkChart(qw422016, benchCharts)
//line pkg/chart/templates/template.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line pkg/chart/templates/template.qtpl:97
}

//line pkg/chart/templates/template.qtpl:97
func BenchmarkChart(benchCharts []shared.BenchCharts) string {
//line pkg/chart/templates/template.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/chart/templates/template.qtpl:97
	WriteBenchmarkChart(qb422016, benchCharts)
//line pkg/chart/templates/template.qtpl:97
	qs422016 := string(qb422016.B)
//line pkg/chart/templates/template.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/chart/templates/template.qtpl:97
	return qs422016
//line pkg/chart/templates/template.qtpl:97
}

//line pkg/chart/templates/template.qtpl:99
func streamrenderChart(qw422016 *qt422016.Writer, chart *charts.Bar) {
//line pkg/chart/templates/template.qtpl:99
	qw422016.N().S(`
    `)
//line pkg/chart/templates/template.qtpl:101
	var buf bytes.Buffer
	chart.Render(&buf)
	content := buf.String()

	// Extract just the chart div and script content
	divStart := strings.Index(content, "<div class=\"container\">")
	scriptEnd := strings.LastIndex(content, "</script>")

	var chartContent string
	if divStart >= 0 && scriptEnd >= 0 {
		// Find the div item with fixed width and height
		divItemStart := strings.Index(content, "<div class=\"item\"")
		divItemEnd := strings.Index(content[divItemStart:], ">") + divItemStart

		if divItemStart >= 0 && divItemEnd > divItemStart {
			// Replace the fixed width and height with responsive values
			beforeDivItem := content[divStart:divItemStart]
			afterDivItem := content[divItemEnd+1 : scriptEnd+9] // +9 to include </script>

			// Create responsive div
			chartId := strings.Split(strings.Split(content[divItemStart:divItemEnd], "id=\"")[1], "\"")[0]
			responsiveDiv := "<div class=\"item\" id=\"" + chartId + "\" style=\"width:100%;height:500px;\">"

			chartContent = beforeDivItem + responsiveDiv + afterDivItem
		} else {
			// Fallback to original extraction if we can't find the item div
			chartContent = content[divStart : scriptEnd+9]
		}
	}

//line pkg/chart/templates/template.qtpl:130
	qw422016.N().S(`
    `)
//line pkg/chart/templates/template.qtpl:131
	qw422016.N().S(chartContent)
//line pkg/chart/templates/template.qtpl:131
	qw422016.N().S(`
`)
//line pkg/chart/templates/template.qtpl:132
}

//line pkg/chart/templates/template.qtpl:132
func writerenderChart(qq422016 qtio422016.Writer, chart *charts.Bar) {
//line pkg/chart/templates/template.qtpl:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/chart/templates/template.qtpl:132
	streamrenderChart(qw422016, chart)
//line pkg/chart/templates/template.qtpl:132
	qt422016.ReleaseWriter(qw422016)
//line pkg/chart/templates/template.qtpl:132
}

//line pkg/chart/templates/template.qtpl:132
func renderChart(chart *charts.Bar) string {
//line pkg/chart/templates/template.qtpl:132
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/chart/templates/template.qtpl:132
	writerenderChart(qb422016, chart)
//line pkg/chart/templates/template.qtpl:132
	qs422016 := string(qb422016.B)
//line pkg/chart/templates/template.qtpl:132
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/chart/templates/template.qtpl:132
	return qs422016
//line pkg/chart/templates/template.qtpl:132
}
