import { defineConfig, type PluginOption } from 'vite'
import vue from '@vitejs/plugin-vue'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { createHtmlPlugin } from 'vite-plugin-html'
import fs from 'node:fs'
import zlib from 'node:zlib'
import path from 'path'
import { parseHTML } from 'linkedom'

const inlineFaviconPlugin = (): PluginOption => {
  return {
    name: 'inline-favicon',
    enforce: 'pre',
    transformIndexHtml(html: string) {
      const { document } = parseHTML(html)
      const link = document.querySelector('link[rel="icon"]')

      if (!link) {
        return html
      }

      const href = link.getAttribute('href')
      if (!href) return html

      // Try to resolve the file path, checking the public directory if needed
      let faviconPath = path.resolve(__dirname, href)

      if (!fs.existsSync(faviconPath)) {
        faviconPath = path.resolve(__dirname, 'public', href)
      }

      if (!fs.existsSync(faviconPath)) {
        console.warn(`[inline-favicon] Could not locate favicon: ${href}`)
        return html
      }

      const source = fs.readFileSync(faviconPath, 'utf-8')
      link.setAttribute('href', `data:${link.getAttribute('type')},${encodeURIComponent(source)}`)

      return '<!DOCTYPE html>' + document.documentElement.outerHTML
    },
  }
}

const appendVizbDataScriptTag = (html: string): string => {
  const { document } = parseHTML(html)

  const script = document.createElement('script')
  script.type = 'text/javascript'
  // Custom Go-template delimiters: echarts-gl's clay.gl GLSL shaders use {{ }}
  // for loop unrolling, which would otherwise collide with html/template parsing.
  script.textContent = `window.VIZB_VERSION = [[VIZB .Version VIZB]]; window.VIZB_DATA = [[VIZB .Data VIZB]]; window.VIZB_DATA_URL = [[VIZB .DataURL VIZB]];`

  document.head.appendChild(script)

  return '<!DOCTYPE html>' + document.documentElement.outerHTML
}

// echarts-gl bundles the clay.gl WebGL engine, inflating the single-file JS to
// ~1.2MB. Store it gzip-compressed + base64 and inflate at runtime via the
// browser's DecompressionStream, cutting the emitted HTML to ~0.5MB.
const compressBundlePlugin = (): PluginOption => {
  const distHtmlPath = path.resolve(__dirname, 'dist/index.html')

  return {
    name: 'compress-bundle',
    apply: 'build',
    closeBundle() {
      if (!fs.existsSync(distHtmlPath)) return

      const html = fs.readFileSync(distHtmlPath, 'utf-8')
      const match = html.match(/<script type=module[^>]*>([\s\S]*?)<\/script>/)
      if (!match) {
        console.warn('[compress-bundle] No module script found, skipping compression.')
        return
      }

      const js = match[1] ?? ''
      const b64 = zlib.gzipSync(Buffer.from(js, 'utf-8'), { level: 9 }).toString('base64')

      // Module bootstrap (deferred, like the original entry): decode base64 ->
      // gunzip -> import as a module blob. Deferral guarantees the VIZB_DATA
      // script in <head> has run before the app module evaluates.
      const bootstrap =
        `<script type=module>` +
        `const b=Uint8Array.from(atob("${b64}"),c=>c.charCodeAt(0));` +
        `const s=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"));` +
        `const code=await new Response(s).text();` +
        `const u=URL.createObjectURL(new Blob([code],{type:"text/javascript"}));` +
        `await import(u);URL.revokeObjectURL(u);` +
        `</script>`

      fs.writeFileSync(distHtmlPath, html.slice(0, match.index) + bootstrap + html.slice(match.index! + match[0].length), 'utf-8')
    },
  }
}

const benchmarkUiGoWrapperPlugin = (): PluginOption => {
  const distHtmlPath = path.resolve(__dirname, 'dist/index.html')
  const goFilePath = path.resolve(__dirname, '..', 'pkg', 'template', 'vizb-ui.gen.go')

  return {
    name: 'benchmark-ui-go-wrapper',
    apply: 'build',
    closeBundle() {
      if (!fs.existsSync(distHtmlPath)) {
        console.warn(
          `[benchmark-ui-go-wrapper] Unable to find ${distHtmlPath}, skipping Go wrapper generation.`
        )
        return
      }

      const htmlContent = fs.readFileSync(distHtmlPath, 'utf-8')
      const htmlWithState = appendVizbDataScriptTag(htmlContent)

      // Escape backticks for Go raw string literal
      const goRawString = htmlWithState.split('`').join('` + "`" + `')

      const goFileContent = `package template

// Code generated by vite.config.ts; DO NOT EDIT.

const VizbHTMLTemplate = \`${goRawString}\`
`

      fs.writeFileSync(goFilePath, goFileContent, 'utf-8')
    },
  }
}

const singleFile = process.env.SINGLEFILE === 'True'
console.info('SINGLEFILE env var:', process.env.SINGLEFILE)

const plugins: PluginOption[] = [vue()]

if (singleFile) {
  plugins.push(
    inlineFaviconPlugin(),
    viteSingleFile({
      removeViteModuleLoader: true,
      useRecommendedBuildConfig: true,
    }),
    compressBundlePlugin(),
    benchmarkUiGoWrapperPlugin()
  )
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    ...plugins,
    createHtmlPlugin({
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        collapseBooleanAttributes: true,
        removeEmptyAttributes: true,
        minifyCSS: true,
        minifyJS: true,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  esbuild: {
    legalComments: 'none',
    pure: ['console.log', 'console.info', 'console.warn', 'console.debug', 'console.trace'],
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
})
