name: action
on:
  workflow_call:
  workflow_dispatch:

jobs:
  embed-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        if: env.ACT != 'true'
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup embed UI
        if: env.ACT != 'true'
        uses: ./.github/actions/setup-embed-ui

      - name: Upload embedded UI
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v7
        with:
          name: action-embedded-ui-${{ github.sha }}
          path: pkg/template/vizb-ui.gen.go
          if-no-files-found: error

  stateless:
    needs: embed-ui
    if: ${{ always() && needs.embed-ui.result == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        if: env.ACT != 'true'
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download embedded UI
        if: env.ACT != 'true'
        uses: actions/download-artifact@v8
        with:
          name: action-embedded-ui-${{ github.sha }}
          path: pkg/template

      - name: Build vizb
        if: env.ACT != 'true'
        run: go build -o ./bin/vizb .

      - name: Run action (stateless)
        uses: ./
        with:
          file: examples/go/hash.txt
          output-html: index.html
          vizb-binary: ./bin/vizb

  stateful:
    needs: embed-ui
    if: ${{ always() && needs.embed-ui.result == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        if: env.ACT != 'true'
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download embedded UI
        if: env.ACT != 'true'
        uses: actions/download-artifact@v8
        with:
          name: action-embedded-ui-${{ github.sha }}
          path: pkg/template

      - name: Build vizb
        if: env.ACT != 'true'
        run: go build -o ./bin/vizb .

      - name: Generate previous JSON
        uses: ./
        with:
          name: Hash
          file: examples/go/hash.txt
          output-json: results/prev/hash.json
          vizb-binary: ./bin/vizb

      - name: Run action (stateful)
        uses: ./
        with:
          name: HTTP Frameworks Comparisons
          group-pattern: x_n
          sort: asc
          file: examples/go/http-routing.txt
          merge-dir: results/prev
          output-html: index.html
          output-json: results/bench.json
          vizb-binary: ./bin/vizb
