name: deploy-rust-examples
on:
  push:
    branches: [main]
    paths:
      - examples/rust/**
      - action.yml
      - .github/workflows/test-action.yml
      - .github/workflows/deploy-examples-rust.yml
  workflow_run:
    workflows: [Release]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-action.yml

  convert:
    needs: test
    strategy:
      matrix:
        include:
          - output: criterion
            bench-file: criterion.txt
            name: "Bubble vs Insertion Sort (Criterion)"
            group-regex: "x/n=(?<y>.*)"
            scale: "log"
            parser: rs:criterion

          - output: divan
            bench-file: divan.txt
            name: "Bubble vs Insertion Sort (Divan)"
            group-pattern: "x__y"
            scale: "log"
            parser: rs:divan

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ${{ matrix.name }}
        uses: ./
        with:
          bench-file: examples/rust/${{ matrix.bench-file }}
          name: ${{ matrix.name }}
          group-pattern: ${{ matrix.group-pattern }}
          group-regex: ${{ matrix.group-regex }}
          scale: ${{ matrix.scale }}
          output-json: ${{ matrix.output }}.json
          parser: ${{matrix.parser}}
          sort: asc

      - name: Uploading json artifacts
        uses: actions/upload-artifact@v4
        with:
          name: json-${{ matrix.output }}
          path: ${{ matrix.output }}.json

  merge-deploy:
    needs: convert
    permissions:
      contents: write
    uses: ./.github/workflows/merge-deploy-examples.yml
    with:
      language: rust
