name: deploy-go-examples
on:
  push:
    branches: [main]
    paths:
      - examples/go/**
      - action.yml
      - .github/workflows/test-action.yml
      - .github/workflows/deploy-examples-go.yml
  workflow_run:
    workflows: [Release]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-action.yml

  convert:
    name: Convert Go Benchmarks
    needs: test
    strategy:
      matrix:
        include:
          - output: 00-decode
            bench-file: 00-decode-encode
            name: "Decode"
            description: "Decode Performance Comparison"
            group-regex: "/text=(?<n>.*)/level=(?<x>.*)/size=(?<y>.*)"
            filter: "Decode"
            scale: "log"

          - output: 01-encode
            bench-file: 00-decode-encode
            name: "Encode"
            description: "Encode Performance Comparison"
            group-regex: "/text=(?<n>.*)/level=(?<x>.*)/size=(?<y>.*)"
            filter: "Encode"
            scale: "log"

          - output: 02-hash
            bench-file: 01-hash
            name: "Hashing"
            description: "Comparison of different hash functions"
            group-regex: "Hashing64(?<x>.*)"
            scale: "log"

          - output: 03-http-routing
            bench-file: 02-http-routing
            name: "HTTP Routing"
            description: "Performance comparison of popular Go HTTP Routers"
            group-pattern: "x_n"
            scale: "log"

          - output: 04-serialization
            bench-file: 03-serialization
            name: "Serialization"
            description: "Comparison of different serialization methods"
            group-regex: "(?<x>.*)By(?<y>.*)"
            scale: "log"

          - output: 05-validator
            bench-file: 04-validator
            name: "Validator"
            description: ""
            group-regex: "(?<y>.*?)(?:(?<x>Success|Failure)(?<n>.*)|$)"
            scale: "log"

          - output: 06-varmq
            bench-file: 05-varmq
            name: "Varmq"
            description: "Variadic Queue Benchmark"
            group-pattern: "x/y"
            scale: "log"

          - output: 07-worker-pools
            bench-file: 06-worker-pools
            name: "Worker Pools"
            description: "Performance comparison of different worker pool implementations"
            group-pattern: "n/y/x"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ${{ matrix.name }}
        uses: ./
        with:
          bench-file: examples/go/${{ matrix.bench-file }}.txt
          name: ${{ matrix.name }}
          description: ${{ matrix.description }}
          group-pattern: ${{ matrix.group-pattern }}
          group-regex: ${{ matrix.group-regex }}
          filter: ${{ matrix.filter }}
          scale: ${{ matrix.scale }}
          output-json: ${{ matrix.output }}.json
          sort: asc

      - name: Uploading json artifacts
        uses: actions/upload-artifact@v4
        with:
          name: json-${{ matrix.output }}
          path: ${{ matrix.output }}.json

  merge-deploy:
    name: Merge Go Benchmarks
    needs: convert
    permissions:
      contents: write
    uses: ./.github/workflows/merge-deploy-examples.yml
    with:
      language: go
