name: Embed UI

on:
  workflow_call:

permissions:
  contents: read
  actions: write

jobs:
  generate:
    runs-on: ubuntu-slim
    concurrency:
      group: embed-ui-${{ github.sha }}
      queue: max
    steps:
      - uses: actions/checkout@v7

      - name: Setup embed UI
        uses: ./.github/actions/setup-embed-ui
