name: test-action
on: workflow_dispatch

jobs:
  stateless:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Run action (stateless)
        uses: ./
        with:
          bench-file: examples/bench/hash.txt
          output-html: index.html

  stateful:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Generate previous JSON
        uses: ./
        with:
          name: Hash
          bench-file: examples/bench/hash.txt
          output-json: results/prev/hash.json

      - name: Run action (stateful)
        uses: ./
        with:
          name: HTTP Frameworks Comparisons
          group-pattern: x_n
          sort: asc
          bench-file: examples/bench/http-routing.txt
          merge-dir: results/prev
          output-html: index.html
          output-json: results/bench.json
