name: test-action
on: workflow_dispatch

jobs:
  stateless:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Run action (stateless)
        uses: ./
        with:
          bench-file: examples/bench/hash.txt
          output-html: index.html

  stateful:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup previous data
        run: |
          mkdir -p results/prev
          cp examples/jsons/hash.json results/prev/

      - name: Run action (stateful)
        uses: ./
        with:
          bench-file: examples/bench/hash.txt
          merge-dir: results/prev
          output-html: index.html
          output-json: results/bench.json
